### ISSUE TITLE
Add initial support for verifiable presentations

### ISSUE THREAD

**Issue by nanderstabel** [impierce/openid4vc#9]
### Description

Add initial support for verifiable presentations. 

This Issue involves adding support for the `vp_token` `response_type` and `presentation_definition` parameter in the SIOP library, as described in the [OpenID for Verifiable Presentations (OpenID4VP) specification](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html). When the `vp_token` response type is set, the Provider should generate a presentation of verifiable credentials based on the `presentation_definition` parameter in the request. The Relying Party should then be able to verify the presentation and authenticate the user based on the claims presented.

This implementation should initially be following the IOTA DID method.

### Motivation

Apart from the SIOPv2 specification, this library should also be able to support the OpenID for Verifiable Presentations specification. The initial implementation as described above will also allow for testing this library against external Client libraries.

### Resources

[OpenID for Verifiable Presentations (OpenID4VP) specification](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html)
#4 

### To-do List

- [ ] Add a `PresentationDefinition` struct that can be deserialized from a `SiopRequest`
- [ ] Add a `VerifiablePresentation` struct that can be build from a `PresentationDefinition`
- [ ] Provide a `presentation_submission` parameter alongside the new `vp_token` in the `SiopResponse`
- [ ] Verifiable Presentations functionality should be behind a `openid4vp` feature flag
